name: medsage
channels:
  - pytorch
  - nvidia
  - conda-forge
  - https://conda.anaconda.org/conda-forge
dependencies:
  - _openmp_mutex=4.5
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - cpython=3.11.14
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=13.0.85
  - cuda-runtime=12.1.0
  - cuda-version=13.0
  - faiss-gpu=1.11.0
  - filelock=3.20.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - icu=75.1
  - jinja2=3.1.6
  - ld_impl_linux-64=2.44
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.15.1.6
  - libcurand=10.4.0.35
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libexpat=2.7.1
  - libfaiss=1.11.0
  - libffi=3.4.6
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libhwloc=2.12.1
  - libiconv=1.18
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libnpp=12.0.2.50
  - libnsl=2.0.1
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libsqlite=3.50.4
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=2.41.2
  - libxcrypt=4.4.36
  - libxml2=2.15.0
  - libxml2-16=2.15.0
  - libzlib=1.3.1
  - llvm-openmp=15.0.7
  - markupsafe=3.0.3
  - mkl=2023.0.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - networkx=3.5
  - numpy=1.26.4
  - ocl-icd=2.3.3
  - opencl-headers=2025.06.13
  - openssl=3.5.4
  - packaging=25.0
  - pandas=2.3.3
  - pip=25.2
  - python=3.11.14
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.11
  - pytorch=2.5.1
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pytz=2025.2
  - pyyaml=6.0.3
  - readline=8.2
  - setuptools=80.9.0
  - six=1.17.0
  - tbb=2021.13.0
  - tk=8.6.13
  - torchtriton=3.1.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - wheel=0.45.1
  - yaml=0.2.5
  - pip:
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.1
      - aiosignal==1.4.0
      - altair==5.5.0
      - annotated-types==0.7.0
      - anyio==4.11.0
      - attrs==25.4.0
      - blinker==1.9.0
      - brotli==1.1.0
      - cachetools==6.2.1
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - click==8.3.0
      - dataclasses-json==0.6.7
      - defusedxml==0.7.1
      - fastapi==0.119.1
      - ffmpy==0.6.3
      - filetype==1.2.0
      - fonttools==4.60.1
      - fpdf2==2.8.4
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - gradio==5.49.1
      - gradio-client==1.13.3
      - greenlet==3.2.4
      - groovy==0.1.2
      - h11==0.16.0
      - hf-xet==1.1.10
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.28.1
      - httpx-sse==0.4.3
      - huggingface-hub==0.35.3
      - idna==3.11
      - joblib==1.5.2
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - langchain==0.3.27
      - langchain-classic==1.0.0
      - langchain-community==0.3.31
      - langchain-core==0.3.79
      - langchain-huggingface==0.3.1
      - langchain-nvidia-ai-endpoints==0.3.18
      - langchain-text-splitters==0.3.11
      - langgraph==1.0.0
      - langgraph-checkpoint==2.1.2
      - langgraph-prebuilt==1.0.0
      - langgraph-sdk==0.2.9
      - langsmith==0.4.37
      - markdown-it-py==4.0.0
      - marshmallow==3.26.1
      - mdurl==0.1.2
      - multidict==6.7.0
      - mypy-extensions==1.1.0
      - narwhals==2.9.0
      - orjson==3.11.3
      - ormsgpack==1.11.0
      - pillow==11.3.0
      - propcache==0.4.1
      - protobuf==6.33.0
      - pyarrow==21.0.0
      - pydantic==2.11.10
      - pydantic-core==2.33.2
      - pydantic-settings==2.11.0
      - pydeck==0.9.1
      - pydub==0.25.1
      - pygments==2.19.2
      - python-dotenv==1.1.1
      - python-multipart==0.0.20
      - rank-bm25==0.2.2
      - referencing==0.37.0
      - regex==2025.9.18
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - rich==14.2.0
      - rpds-py==0.27.1
      - ruff==0.14.1
      - safehttpx==0.1.6
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - scipy==1.16.2
      - semantic-version==2.10.0
      - sentence-transformers==5.1.1
      - shellingham==1.5.4
      - smmap==5.0.2
      - sniffio==1.3.1
      - sqlalchemy==2.0.44
      - starlette==0.48.0
      - streamlit==1.50.0
      - sympy==1.13.1
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - tokenizers==0.22.1
      - toml==0.10.2
      - tomlkit==0.13.3
      - tornado==6.5.2
      - tqdm==4.67.1
      - transformers==4.57.1
      - typer==0.20.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - urllib3==2.5.0
      - uvicorn==0.38.0
      - uvloop==0.22.1
      - watchdog==6.0.0
      - watchfiles==1.1.1
      - websockets==15.0.1
      - xxhash==3.6.0
      - yarl==1.22.0
      - zstandard==0.25.0
prefix: /home/adidas/.conda/envs/medsage
